version: '3.8'

services:
  app:
    image: farah16629/myapp:latest
    container_name: myapp-prod
    ports:
      - "80:8080"
    environment:
      - ENV=production
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus-prod
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-prod
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
