services:
  app:
    image: yourdockerhubusername/myapp:staging
    container_name: my-ci-cd-pipeline_app_1
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus
    container_name: my-ci-cd-pipeline_prometheus_1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: my-ci-cd-pipeline_grafana_1
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
