FROM jenkins/jenkins:lts

USER root

# Install Docker CLI inside Jenkins container
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# Allow Jenkins to use the Docker socket
RUN usermod -aG docker jenkins

USER jenkins
