version: '3.8'

services:
  app:
    image: farah16629/myapp:staging
    container_name: my-ci-cd-pipeline_app_1
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus
    container_name: my-ci-cd-pipeline_prometheus_1
    volumes:
      - ./prometheus.yml:/etc/prometheus/config.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"


volumes:
  prometheus_data:
