version: '3.8'

services:
  app:
    image: farah16629/myapp:latest
    ports:
      - "80:8080"
    environment:
      - ENV=production
    restart: always
    networks:
      - my-ci-cd-pipeline-net

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    container_name: prometheus-prod
    ports:
      - "9090:9090"
    depends_on:
      - app
    restart: always
    networks:
      - my-ci-cd-pipeline-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-prod
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always
    networks:
      - my-ci-cd-pipeline-net

networks:
  my-ci-cd-pipeline-net:
    external: true
