global:
  scrape_interval: 5s   # How often to scrape targets by default
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    metrics_path: /metrics   # The endpoint your Python app exposes metrics on
    static_configs:
      - targets: ['my-ci-cd-pipeline_app_1:8080']
